(WIP) Hanging Offsets
ArtixAllMighty/HangMan pull request #3
Opened 2021-09-10 23:01 UTC by uSkizzik

- Changes the default hanging offset to a new one
- [WIP] Adds offsets for vanilla entities via a map to allow mods to add their own entities if they care enough

2021-09-10 23:07 UTC, uSkizzik commented on src/main/java/subaraki/hangman/entity/HangEntityDummy.java
> +        return -1.42D;
Looks better in my opinion.
Also, makes the noose look the same on both players and zombies.

2021-09-10 23:08 UTC, uSkizzik commented on build.gradle
> +        client2 {
Another run configuration to run a second client for testing purposes.

2021-09-11 14:39 UTC, ArtixAllMighty requested changes
This PR has the build gradle changed.
Thus has nothing to do with the hanging offset, and should be either its won PR, or should be kept locally, for personal use, as I already have a second run set up from my IDE.

2021-09-20 16:42 UTC, ArtixAllMighty commented
this feature has been implemented together with the white list

2021-09-20 16:42 UTC, closed without merging